language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.9
  - DJANGO=1.10
install:
  - pip install -q Django==$DJANGO
  - pip install -q -e .
script:
  - python setup.py test
