language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.9
  - DJANGO=1.10
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - python setup.py test
